// Mapeamento oficial extraído de "elementos e subelementos.xlsx".
const names = {
  '01': 'Aposentadorias. Reserva Remunerada e Reformas',
  '03': 'Pensões',
  '04': 'Contratação por Tempo Determinado',
  '07': 'Contrib. Entid. Fechadas de Previdência',
  '08': 'Outros Benefícios Assistenciais',
  '11': 'Vencim. e Vantagens Fixas - Pessoal Civil',
  '12': 'Vencim. e Vantagens Fixas - Pessoal Militar',
  '13': 'Obrigações Patronais',
  '14': 'Diárias - Civil',
  '15': 'Diárias - Militar',
  '16': 'Outras Despesas Variáveis-Pessoal Civil',
  '17': 'Outras Despesas Variáveis-Pessoal Militar',
  '18': 'Auxílio Financeiro a Estudantes',
  '19': 'Auxílio Fardamento',
  '20': 'Auxílio Financeiro a Pesquisadores',
  '21': 'Juros sobre a Dívida por Contrato',
  '22': 'Outros Encargos sobre Dívida por Contrato',
  '30': 'Material de Consumo',
  '31': 'Premiações Culturais. Artísticas. Científicas. Desportivas e Outras',
  '32': 'Material. Bem ou Serviço de Distribuição Gratuita',
  '33': 'Passagens e Despesas com Locomoção',
  '34': 'Outras Desp. Pessoal Decor. Contr. Terceirização',
  '35': 'Serviços de Consultoria',
  '36': 'Outros Serv. Terceiros - Pessoa Física',
  '37': 'Locação de Mão-de-Obra',
  '39': 'Outros Serviços Terceiros - Pessoa Jurídica',
  '40': 'Serviços de Tecnologia da Informação e Comunicação - Pessoa Jurídica',
  '41': 'Contribuições',
  '42': 'Auxílios',
  '43': 'Subvenções Sociais',
  '45': 'Subvenções Econômicas',
  '46': 'Auxílio-Alimentação',
  '47': 'Obrigações Tributárias e Contributivas',
  '48': 'Outros Auxílios Financeiros Pessoas Físicas',
  '49': 'Auxílio-Transporte',
  '51': 'Obras e Instalações',
  '52': 'Equipamentos e Material Permanente',
  '59': 'Pensões Especiais',
  '61': 'Aquisição de Imóveis',
  '62': 'Aquisição de Produtos para Revenda',
  '63': 'Aquisição de Títulos de Crédito',
  '65': 'Const. ou Aumento de Capital de Empresas',
  '66': 'Concessão de Empréstimos e Financiam.',
  '67': 'Depósitos Compulsórios',
  '71': 'Principal da Dívida Contrat. Resgatado',
  '83': 'Despesas Decorrentes de Contrato PPP. exceto subvenções econômicas. aporte e fundo garantidor',
  '85': 'Transferência por meio de Contrato de Gestão',
  '86': 'Compensações a Regimes de Previdência',
  '91': 'Sentenças Judiciais',
  '92': 'Despesas de Exercícios Anteriores',
  '93': 'Indenizações e Restituições',
  '94': 'Indenizações e Restituições Trabalhistas',
  '96': 'Ressarcimento Despesa Pessoal Requisitado',
}

export function getElementoDespesa(subElementoCode) {
  const subelemento = String(subElementoCode ?? '').replace(/\D/g, '')
  const code = subelemento.length >= 6 ? subelemento.slice(4, 6) : ''
  return { code, name: names[code] ?? 'Elemento não informado' }
}
