export const empenhoFields = [
  ['nmtipoempenho', 'Tipo de empenho', 'Identificação'],
  ['nunotaempenho', 'Nota de empenho', 'Identificação'],
  ['dtlancamento', 'Data de lançamento', 'Identificação'],
  ['nunotaempenhooriginal', 'Nota original', 'Identificação'],
  ['nuidentificacao', 'Identificação', 'Identificação'],
  ['cdorgao', 'Código do órgão', 'Órgão e unidade gestora'],
  ['nmorgao', 'Órgão', 'Órgão e unidade gestora'],
  ['cdunidadegestora', 'Código da unidade gestora', 'Órgão e unidade gestora'],
  ['nmunidadegestora', 'Unidade gestora', 'Órgão e unidade gestora'],
  ['nmcredor', 'Credor', 'Credor e contratação'],
  ['demodalidadeempenho', 'Modalidade do empenho', 'Credor e contratação'],
  ['nmmodalidade', 'Modalidade de licitação', 'Credor e contratação'],
  ['detipocontrato', 'Tipo de contrato', 'Credor e contratação'],
  ['nucontrato', 'Contrato', 'Credor e contratação'],
  ['nucontratosicop', 'Contrato SICOP', 'Credor e contratação'],
  ['cdfuncao', 'Código da função', 'Classificação orçamentária'],
  ['nmfuncao', 'Função', 'Classificação orçamentária'],
  ['cdsubfuncao', 'Código da subfunção', 'Classificação orçamentária'],
  ['nmsubfuncao', 'Subfunção', 'Classificação orçamentária'],
  ['cdprograma', 'Código do programa', 'Classificação orçamentária'],
  ['nmprograma', 'Programa', 'Classificação orçamentária'],
  ['cdacao', 'Código da ação', 'Classificação orçamentária'],
  ['nmacao', 'Ação', 'Classificação orçamentária'],
  ['cdsubacao', 'Código da subação', 'Classificação orçamentária'],
  ['nmsubacao', 'Subação', 'Classificação orçamentária'],
  ['cdfonterecurso', 'Código da fonte', 'Classificação orçamentária'],
  ['nmfonterecurso', 'Fonte de recurso', 'Classificação orçamentária'],
  ['cdsubelemento', 'Código do elemento', 'Classificação orçamentária'],
  ['nmsubelemento', 'Elemento', 'Classificação orçamentária'],
  ['nutransferenciadespesa', 'Transferência de despesa', 'Transferências'],
  ['nutransferenciaespecial', 'Transferência especial', 'Transferências'],
  ['dehistoricoempenho', 'Histórico do empenho', 'Histórico'],
  ['vlempenho', 'Valor empenhado', 'Valor'],
]

export const empenhoFieldKeys = empenhoFields.map(([key]) => key)
